services:
  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_service
    restart: unless-stopped

    dns:
      - 1.1.1.1
      - 8.8.8.8

    networks:
      macvlan:
        ipv4_address: 10.12.144.6

    volumes:
      - nginx-volume/data:/data
      - nginx-volume/letsencrypt:/etc/letsencrypt

    environment:
      TZ: Europe/Amsterdam

networks:
  macvlan:
    external: true

volumes:
  nginx-volume:
    external: true